spring.application.name=TiengAnhMoiNgay
spring.datasource.url=jdbc:mysql://localhost:3306/TiengAnhMoiNgay
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Spring Security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# OAuth2
spring.security.oauth2.client.registration.google.client-id=261464617334-74al5vbuq6vo4j4di711fe1e3pj0ajd7.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

server.error.path=/error

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=moshung090103@gmail.com
spring.mail.password=acetcjpaslidemtw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB


